version: "3"

services:
  api:
    build: ./api
    container_name: api
    volumes:
      - ./api/:/app/

  ui:
    build: ./ui
    container_name: ui

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 5000:5000
      - 80:3000
