<template>
  <router-view />
</template>

<script>
export default { name: "App" };
</script>

<style lang="scss">
$rad: 5px;
$mainColor: grey;
$offsetColor: #ddd;
$transition: cubic-bezier(0.075, 0.82, 0.165, 1) 0.8s;

@media only screen and (max-width: 768px) {
  .container {
    width: auto;
  }
}

@media only screen and (min-width: 1200px) {
  .container {
    width: 1200px;
  }
}
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

#nav {
  padding: 30px;

  a {
    padding: 5px 15px 5px 15px;
    margin: -1px;
    border: 1px solid $mainColor;
    color: $mainColor;
    text-decoration: none;

    &:first-child {
      border-radius: $rad 0 0 $rad;
    }

    &:last-child {
      border-radius: 0 $rad $rad 0;
    }

    &:hover {
      background-color: darken(white, 10%);
    }

    &.router-link-exact-active {
      color: white;
      background-color: $mainColor;

      &:hover {
        background-color: $mainColor;
      }
    }
  }
}

blockquote {
  overflow: hidden;
  padding-right: 1.5em;
  padding-left: 1.5em;
  margin-left: 0;
  margin-right: 0;
  font-style: italic;
  border-left: 5px solid #ccc;
}

textarea {
  margin-top: 10px;
  font-family: inherit;
  width: 90%;
  height: 200px;
  border: 1px solid #ddd;
  border-radius: 5px;
  padding: 20px;
  resize: none;
}

figure {
  &.media {
    position: relative;
    height: 500px;
  }

  iframe {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
  }
}

.marker-green {
  background-color: #62f962;
}

.marker-pink {
  background-color: #fc7899;
}

.marker-blue {
  background-color: #72ccfd;
}

.pen-red {
  background-color: transparent;
  color: #e71313;
}

.pen-green {
  color: #128a00;
  background-color: transparent;
}
.container {
  text-align: center;
  margin: 60px auto 0px auto;
}

.flex {
  display: flex;
}

.grid {
  display: grid;
}

.hr {
  margin: 10px auto;
  width: auto;
  height: 1px;
  background-color: #aaa;
}

footer {
  color: #777;
  text-align: center;
  margin: 30px auto 10px auto;
}

label {
  margin: 20px 0 0 0;
  display: block;
}

input {
  border: 1px solid #ddd;
  border-radius: 5px;
  font-size: 15px;
  padding: 5px 10px;
  margin: 10px 0;
  width: 50%;
  height: 35px;
  transition: border $transition, box-shadow $transition;

  &:focus {
    border: 1px solid darken(#ddd, 20%);
    box-shadow: inset 0px 0px 4px darken(#ddd, 20%);
  }
}

.shake-horizontal {
  -webkit-animation: shake-horizontal 0.4s
    cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
  animation: shake-horizontal 0.4s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-5-16 0:4:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}
@keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
    transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
    transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
    transform: translateX(-8px);
  }
}

input[type="checkbox"],
input[type="radio"] {
  width: 30px;
  margin-right: 10px;
}

.mx-auto {
  margin-left: auto;
  margin-right: auto;
}

.my-auto {
  margin-top: auto;
  margin-bottom: auto;
}

.mb-auto {
  margin-bottom: auto;
}

.mt-auto {
  margin-top: auto;
}

.mr-auto {
  margin-right: auto;
}

.ml-auto {
  margin-left: auto;
}

button,
.button {
  padding: 10px 20px;
  font-family: inherit;
  font-size: 15px;
  border: 1px solid #ddd;
  border-radius: 5px;
  cursor: pointer;
  background-color: #eee;
  transition: background-color $transition;

  &:hover {
    background-color: darken(#ddd, 20%);
  }

  &.black {
    transition: background-color $transition, color $transition;
    &:hover {
      color: white;
      background-color: black;
    }
  }
}
</style>
