# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      - name: Deploy Multiple Docker Images to Heroku Apps
        # You may pin to the exact commit or the version.
        # uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@a4590bf326a12190449bdd4c07657e048b1ca9d7
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          # Email linked to your Heroku account
          email: stevenjpx2@gmail.com
          # Your Heroku API Key
          api_key: ${{ secrets.HEROKU_API }}
          # Your Heroku App Name
          app_name: stevenjohn-co
          # docker-compose File Path
          docker_compose_file: docker-compose.yml
          # List of Docker Images generated from docker-compose and Heroku app names with type
          heroku_apps: '[{"imagename":"api","appname":"api","apptype":""}, {"imagename":"ui","appname":"ui","apptype":""}, {"imagename":"nginx","appname":"nginx","apptype":""}]'
